### ISSUE TITLE
Moving certain animals around creates massive amount of duplicate AI goals

### ISSUE THREAD

**Issue by Hubry** [team-abnormals/environmental#226]
Every time an animal enters a different chunk a new AI goal is added, which means moving around adds a massive amount of duplicate AI goals ([code here](https://github.com/team-abnormals/environmental/blob/5d4716e316273022576b45ff43f4c0ced60c5a2f/src/main/java/com/minecraftabnormals/environmental/core/other/EnvironmentalEvents.java#L338-L356)).

Combined with Performant (this was reported on Vazkii's discord by a confused user losing foxhounds out of nowhere) you get stuff like this in the log:

```
[14Jul2021 17:57:02.675] [Server thread/INFO] [com.performant.coremod.Performant/]: AI tried to add over 100 goals, removing entity
java.lang.Exception: Too many AI Tasks
    at com.performant.coremod.entity.ai.CustomGoalSelector.func_75776_a(CustomGoalSelector.java:213) ~[performant:1.16.2-5-3.66m]
    at com.minecraftabnormals.environmental.core.other.EnvironmentalEvents.onEvent(EnvironmentalEvents.java:302) ~[environmental:1.0.0]
    at net.minecraftforge.eventbus.ASMEventHandler_990_EnvironmentalEvents_onEvent_EnteringChunk.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
    at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:325) ~[?:?]
    at net.minecraft.world.server.ServerWorld.func_217464_b(ServerWorld.java:673) ~[?:?]
    at net.minecraft.entity.LivingEntity.handler$zpp006$tick(LivingEntity.java:3483) ~[?:?]
    at net.minecraft.entity.LivingEntity.func_70071_h(LivingEntity.java) ~[?:?]
    at net.minecraft.entity.MobEntity.func_70071_h(MobEntity.java:300) ~[?:?]
    at net.minecraft.entity.passive.WolfEntity.func_70071_h(WolfEntity.java:178) ~[?:?]
```

**Comment by Elliegobrr** [comment]
Can confirm, am confused user
