### ISSUE TITLE
Sawmill have broken recipes with Outer End

### ISSUE THREAD

**Issue by Hypsellis** [team-abnormals/environmental#227]
```
[04:29:39] [Render thread/ERROR]: Parsing error loading recipe outer_end:sawmill/azure_stairs_from_azure_stems_sawing
com.google.gson.JsonSyntaxException: Unknown item tag 'outer_end:azure_stem'
	at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:223) ~[?:?]
	at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[?:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_199802_a(Ingredient.java:189) ~[?:?]
	at net.minecraft.item.crafting.SingleItemRecipe$Serializer.func_199425_a_(SingleItemRecipe.java:76) ~[?:?]
	at net.minecraft.item.crafting.SingleItemRecipe$Serializer.func_199425_a_(SingleItemRecipe.java:63) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) [?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$14403/37050228.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$14596/31665639.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) [?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1715) [?:?]
	at net.minecraft.client.Minecraft.lambda$loadWorld$29(Minecraft.java:1804) [?:?]
	at net.minecraft.client.Minecraft$$Lambda$18641/200845811.run(Unknown Source) [?:?]
	at net.minecraft.client.Minecraft.lambda$displayExperimentalConfirmationDialog$30(Minecraft.java:1834) [?:?]
	at net.minecraft.client.Minecraft$$Lambda$18642/1010665156.proceed(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.ConfirmBackupScreen.func_212992_b(SourceFile:40) [?:?]
	at net.minecraft.client.gui.screen.ConfirmBackupScreen$$Lambda$18650/861471485.onPress(Unknown Source) [?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) [?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) [?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$17253/2101184295.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$17252/1040624209.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) [?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$14376/1283226190.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.33.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/1147334625.call(Unknown Source) [forge-1.16.5-36.1.33.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[04:29:40] [Render thread/ERROR]: Parsing error loading recipe outer_end:sawmill/azure_planks_from_vertical_azure_planks_sawing
com.google.gson.JsonSyntaxException: Unknown item 'outer_end:vertical_azure_planks'
	at net.minecraft.item.crafting.Ingredient.lambda$valueFromJson$11(Ingredient.java:216) ~[?:?]
	at net.minecraft.item.crafting.Ingredient$$Lambda$18261/614182520.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:215) ~[?:?]
	at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[?:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_199802_a(Ingredient.java:189) ~[?:?]
	at net.minecraft.item.crafting.SingleItemRecipe$Serializer.func_199425_a_(SingleItemRecipe.java:76) ~[?:?]
	at net.minecraft.item.crafting.SingleItemRecipe$Serializer.func_199425_a_(SingleItemRecipe.java:63) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) [?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$14403/37050228.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$14596/31665639.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) [?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1715) [?:?]
	at net.minecraft.client.Minecraft.lambda$loadWorld$29(Minecraft.java:1804) [?:?]
	at net.minecraft.client.Minecraft$$Lambda$18641/200845811.run(Unknown Source) [?:?]
	at net.minecraft.client.Minecraft.lambda$displayExperimentalConfirmationDialog$30(Minecraft.java:1834) [?:?]
	at net.minecraft.client.Minecraft$$Lambda$18642/1010665156.proceed(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.ConfirmBackupScreen.func_212992_b(SourceFile:40) [?:?]
	at net.minecraft.client.gui.screen.ConfirmBackupScreen$$Lambda$18650/861471485.onPress(Unknown Source) [?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) [?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) [?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$17253/2101184295.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$17252/1040624209.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) [?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$14376/1283226190.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.33.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/1147334625.call(Unknown Source) [forge-1.16.5-36.1.33.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[04:30:22] [Render thread/ERROR]: Found a broken recipe: The Outer End outer_end:sawmill/vertical_azure_planks_from_azure_stems_sawing class com.minecraftabnormals.environmental.common.item.crafting.SawingRecipe
Outputs:
net.minecraft.item.ItemStack: [[4 air minecraft:air]]
Inputs:
net.minecraft.item.ItemStack: [[1 azure_stem outer_end:azure_stem, 1 azure_stripped_stem outer_end:azure_stripped_stem, 1 azure_pith outer_end:azure_pith, 1 azure_stripped_pith outer_end:azure_stripped_pith]]

java.lang.IllegalArgumentException: ItemStack value must not be empty. 4 air minecraft:air
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:184) ~[?:7.7.1.110]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:87) ~[?:7.7.1.110]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:28) ~[?:7.7.1.110]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:94) ~[?:7.7.1.110]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:75) ~[?:7.7.1.110]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipe(RecipeManagerInternal.java:124) [?:7.7.1.110]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipeTyped(RecipeManagerInternal.java:103) [?:7.7.1.110]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:96) [?:7.7.1.110]
	at mezz.jei.recipes.RecipeManagerInternal.<init>(RecipeManagerInternal.java:88) [?:7.7.1.110]
	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:144) [?:7.7.1.110]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:74) [?:7.7.1.110]
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) [?:7.7.1.110]
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) [?:7.7.1.110]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) [?:7.7.1.110]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$16800/301837546.accept(Unknown Source) [?:7.7.1.110]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2894/65583344.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2530/473275716.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:708) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$19836/691245474.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.33.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/1147334625.call(Unknown Source) [forge-1.16.5-36.1.33.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[04:30:22] [Render thread/ERROR]: Found a broken recipe: The Outer End outer_end:sawmill/vertical_azure_planks_from_azure_planks_sawing class com.minecraftabnormals.environmental.common.item.crafting.SawingRecipe
Outputs:
net.minecraft.item.ItemStack: [[1 air minecraft:air]]
Inputs:
net.minecraft.item.ItemStack: [[1 azure_planks outer_end:azure_planks]]

java.lang.IllegalArgumentException: ItemStack value must not be empty. 1 air minecraft:air
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:184) ~[?:7.7.1.110]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:87) ~[?:7.7.1.110]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:28) ~[?:7.7.1.110]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:94) ~[?:7.7.1.110]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:75) ~[?:7.7.1.110]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipe(RecipeManagerInternal.java:124) [?:7.7.1.110]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipeTyped(RecipeManagerInternal.java:103) [?:7.7.1.110]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:96) [?:7.7.1.110]
	at mezz.jei.recipes.RecipeManagerInternal.<init>(RecipeManagerInternal.java:88) [?:7.7.1.110]
	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:144) [?:7.7.1.110]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:74) [?:7.7.1.110]
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147) [?:7.7.1.110]
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140) [?:7.7.1.110]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106) [?:7.7.1.110]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$16800/301837546.accept(Unknown Source) [?:7.7.1.110]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2894/65583344.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2530/473275716.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:708) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1314) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$19836/691245474.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.33.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/1147334625.call(Unknown Source) [forge-1.16.5-36.1.33.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
```

**Comment by Hypsellis** [comment]
I suspect the issue is caused by Lepton and not Environmental, since Lepton adds many recipes to the sawmill and kiln.

**Comment by bageldotjpg** [comment]
Yeah this recipe is not done on Environmental's end
