### ISSUE TITLE
[1.16.5 | 1.1.0] Zombie Villager Texture Missing

### ISSUE THREAD

**Issue by Seikikai** [team-abnormals/environmental#244]
Found This One While Exploring A Cave. Hope You Can Fix It :)

![imagen](https://user-images.githubusercontent.com/54079357/133865486-4e985d48-1e2c-4fee-99fa-43e7e2020933.png)

**Entity**

```
[17sep2021 19:15:23.650] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Zombie Villager has the following entity data: {Brain: {memories: {}}, HurtByTimestamp: 0, ForgeData: {anointeditemschestplateHealthUUID: "", CurseOfVampirismCounter: 5619, anointeditemshelmetMiningSpeedUUID: "", anointeditemshelmetAttackDamageUUID: "", anointeditemsoffhandAttackSpeedUUID: "", anointeditemsoffhandHealthUUID: "", anointeditemschestplateSpeedUUID: "", anointeditemsmainhandAttackSpeedUUID: "", anointeditemsoffhandMiningSpeedUUID: "", anointeditemsleggingsAttackSpeedUUID: "", anointeditemsmainhandSpeedUUID: "", anointeditemsonMainhand: 0b, CurseOfCorrosionCounter: 5619, anointeditemsonFeet: 0b, anointeditemsbootsMiningSpeedUUID: "", anointeditemshelmetSpeedUUID: "", anointeditemschestplateAttackDamageUUID: "", anointeditemsleggingsArmorUUID: "", anointeditemsleggingsAttackDamageUUID: "", anointeditemshelmetHealthUUID: "", anointeditemsleggingsMiningSpeedUUID: "", anointeditemsonOffhand: 0b, anointeditemsmainhandMiningSpeedUUID: "", anointeditemschestplateArmorUUID: "", anointeditemsmainhandHealthUUID: "", anointeditemschestplateAttackSpeedUUID: "", anointeditemsleggingsHealthUUID: "", anointeditemsoffhandAttackDamageUUID: "", anointeditemsonHead: 0b, KnockbackImmunityCounter: 0, CurseOfVampirismParticleCounter: 5619, anointeditemsonChest: 0b, anointeditemsbootsAttackSpeedUUID: "", anointeditemsbootsSpeedUUID: "", anointeditemsonLegs: 0b, anointeditemshelmetAttackSpeedUUID: "", anointeditemsleggingsSpeedUUID: "", anointeditemsbootsAttackDamageUUID: "", anointeditemshelmetArmorUUID: "", anointeditemsmainhandAttackDamageUUID: "", anointeditemsoffhandSpeedUUID: "", anointeditemsoffhandArmorUUID: "", anointeditemsmainhandArmorUUID: "", anointeditemsbootsArmorUUID: "", anointeditemsbootsHealthUUID: "", anointeditemschestplateMiningSpeedUUID: ""}, IsBaby: 0b, Attributes: [{Base: 0.0d, Modifiers: [{Amount: 0.015834774227929664d, Operation: 0, UUID: [I; -400758744, 202393759, -1475600703, -576603260], Name: "Random spawn bonus"}, {Amount: 0.0d, Operation: 0, UUID: [I; -1388444082, -369735865, -1469364516, 1311380548], Name: "KnockBackImmunityTime"}], Name: "minecraft:generic.knockback_resistance"}, {Base: 0.08792743295687222d, Name: "minecraft:zombie.spawn_reinforcements"}, {Base: 0.08d, Name: "forge:entity_gravity"}, {Base: 0.23000000417232513d, Name: "minecraft:generic.movement_speed"}, {Base: 35.0d, Modifiers: [{Amount: 0.07176230201627881d, Operation: 1, UUID: [I; -458735138, 591613737, -1108867312, -1856773098], Name: "Random spawn bonus"}], Name: "minecraft:generic.follow_range"}], Invulnerable: 0b, FallFlying: 0b, PortalCooldown: 0, AbsorptionAmount: 0.0f, InWaterTime: -1, FallDistance: 0.0f, CanUpdate: 1b, DeathTime: 0s, Xp: 0, ForgeCaps: {"structure_gel:gel_entity": {portal: "structure_gel:empty"}, "mekanism:radiation": {radiation: 1.0E-7d}, "twilightforest:cap_shield": {permshields: 0, tempshields: 0}, "citadel:extended_entity_data_citadel": {}}, HandDropChances: [0.085f, 0.085f], PersistenceRequired: 0b, UUID: [I; 42161747, 234504579, -1655606918, -481329478], Tags: ["collective.checked", "nohostilesaroundcampfire.checked"], ConversionTime: -1, Motion: [0.0d, -0.0784000015258789d, 0.0d], Health: 20.0f, LeftHanded: 0b, Air: 300s, OnGround: 1b, CitadelData: {}, Rotation: [313.37762f, 0.0f], HandItems: [{}, {}], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Pos: [313.69999998807907d, 44.0d, 133.69999998807907d], fireType: "fire", CanBreakDoors: 0b, Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0b, VillagerData: {profession: "environmental:carpenter", level: 1, type: "environmental:marsh"}, HurtTime: 0s, DrownedConversionTime: -1}
```

**Latest Log**

```
[17sep2021 19:08:33.786] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: environmental:textures/entity/zombie_villager/type/marsh.png
java.io.FileNotFoundException: environmental:textures/entity/zombie_villager/type/marsh.png
	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:63) ~[?:?]
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:61) ~[?:?]
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureData.func_217799_a(SourceFile:81) ~[?:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_215246_b(SourceFile:57) ~[?:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_195413_a(SourceFile:28) ~[?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_230183_b_(TextureManager.java:94) [?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_229263_a_(TextureManager.java:65) [?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_229269_d_(TextureManager.java:58) [?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) [?:?]
	at net.minecraft.client.renderer.RenderState$TextureState.func_228605_a_(SourceFile:206) [?:?]
	at net.minecraft.client.renderer.RenderState$TextureState$$Lambda$3467/845125464.run(Unknown Source) [?:?]
	at net.minecraft.client.renderer.RenderState.func_228547_a_(SourceFile:32) [?:?]
	at net.minecraft.client.renderer.RenderType$Type$$Lambda$37278/1042483280.accept(Unknown Source) [?:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) [guava-21.0.jar:?]
	at net.minecraft.client.renderer.RenderType$Type.func_228674_b_(RenderType.java:518) [?:?]
	at net.minecraft.client.renderer.RenderType$Type$$Lambda$3531/2019813042.run(Unknown Source) [?:?]
	at net.minecraft.client.renderer.RenderState.func_228547_a_(SourceFile:32) [?:?]
	at net.minecraft.client.renderer.RenderType.func_228631_a_(RenderType.java:280) [?:?]
	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.func_228462_a_(SourceFile:86) [?:?]
	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.getBuffer(SourceFile:45) [?:?]
	at net.minecraft.client.renderer.entity.layers.LayerRenderer.func_229141_a_(SourceFile:31) [?:?]
	at net.minecraft.client.renderer.entity.layers.VillagerLevelPendantLayer.func_225628_a_(SourceFile:75) [?:?]
	at net.minecraft.client.renderer.entity.layers.VillagerLevelPendantLayer.func_225628_a_(SourceFile:30) [?:?]
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:125) [?:?]
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:43) [?:?]
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:18) [?:?]
	at xaero.common.minimap.render.radar.EntityIconPrerenderer.prerender(EntityIconPrerenderer.java:261) [?:21.16.0]
	at xaero.common.minimap.render.radar.EntityIconManager.getEntityHeadTexture(EntityIconManager.java:136) [?:21.16.0]
	at xaero.common.minimap.render.MinimapFBORenderer.renderEntityDotToFBO(MinimapFBORenderer.java:449) [?:21.16.0]
	at xaero.common.minimap.render.MinimapFBORenderer.renderEntityListToFBO(MinimapFBORenderer.java:409) [?:21.16.0]
	at xaero.common.minimap.render.MinimapFBORenderer.renderChunksToFBO(MinimapFBORenderer.java:341) [?:21.16.0]
	at xaero.common.minimap.render.MinimapFBORenderer.renderChunks(MinimapFBORenderer.java:87) [?:21.16.0]
	at xaero.common.minimap.render.MinimapRenderer.renderMinimap(MinimapRenderer.java:125) [?:21.16.0]
	at xaero.common.minimap.MinimapProcessor.onRender(MinimapProcessor.java:150) [?:21.16.0]
	at xaero.common.minimap.MinimapInterfaceInstance.render(MinimapInterfaceInstance.java:28) [?:21.16.0]
	at xaero.common.interfaces.render.InterfaceRenderer.renderInterfaces(InterfaceRenderer.java:55) [?:21.16.0]
	at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPreOverridable(ForgeEventHandler.java:133) [?:21.16.0]
	at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPre(ForgeEventHandler.java:148) [?:21.16.0]
	at net.minecraftforge.eventbus.ASMEventHandler_860_ForgeEventHandler_handleRenderGameOverlayEventPre_Pre.invoke(.dynamic) [?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2629/882585908.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:828) [?:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHelmet(ForgeIngameGui.java:282) [?:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:136) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:472) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.2.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$499/786716359.call(Unknown Source) [forge-1.16.5-36.2.2.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
```

**Comment by thelegitdolt** [comment]
it's only this way with marsh zombie villagers i think, everything else seems to work fine
